version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  uk_server:
    image: nginx
    volumes:
      - ./content/uk:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  us_server1:
    image: nginx
    volumes:
      - ./content/us:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  us_server2:
    image: nginx
    volumes:
      - ./content/us:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  other_server:
    image: nginx
    volumes:
      - ./content/other:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  backup_server:
    image: nginx
    volumes:
      - ./content/backup:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3
